import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";
import Header from "@/components/Header";
import Preloader from "@/components/Preloader";
import Sidebar from "@/components/Sidebar";
import Search from "@/components/Search";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="/assets/css/flaticon.css" />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Preloader />
        <Sidebar />
        <Search />
        <Header />
        <main id="content">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
