import { Plus_Jakarta_Sans, Kumbh_Sans, Quicksand } from "next/font/google";
import "./globals.css";
import BootstrapClient from "./bootstrap-client";
import Footer from "@/components/Footer";
import Header from "@/components/Header";
import Preloader from "@/components/Preloader";
import Sidebar from "@/components/Sidebar";
import Search from "@/components/Search";

export const metadata = {
  title: "ITnnovator",
  description: "Generated by create next app",
  icons: {
    icon: '/favicon.ico',
    apple: '/apple-touch-icon.png',
  },
  manifest: '/site.webmanifest', 
};

const plusJakarta = Plus_Jakarta_Sans({
  subsets: ["latin"],
  variable: "--font-primary",
  display: "swap",
});

const kumbh = Kumbh_Sans({
  subsets: ["latin"],
  variable: "--font-kumbh",
  display: "swap", 
});

const quicksand = Quicksand({
  subsets: ["latin"],
  variable: "--font-quicksand",
  display: "swap",
});

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="/assets/css/flaticon.css" />
      </head>
      <body className={`${plusJakarta.variable} ${kumbh.variable} ${quicksand.variable}`}>
        <BootstrapClient />
        <Preloader />
        <Sidebar />
        <Search />
        <Header />
        <main id="content">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
