import { Plus_Jakarta_Sans, Kumbh_Sans } from "next/font/google";
import "bootstrap/dist/css/bootstrap.min.css";
import "./globals.css";
import Footer from "@/components/Footer";
import Header from "@/components/Header";
import Preloader from "@/components/Preloader";
import Sidebar from "@/components/Sidebar";
import Search from "@/components/Search";
import BootstrapClient from "./bootstrap-client";

export const metadata = {
  title: "ITnnovator",
  description: "Generated by create next app",
};

const plusJakarta = Plus_Jakarta_Sans({
  subsets: ["latin"],
  variable: "--font-primary",
  display: "swap",
});

const kumbh = Kumbh_Sans({
  subsets: ["latin"],
  variable: "--font-kumbh",
  display: "swap",
});

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="/assets/css/flaticon.css" />
      </head>
      <body className={`${plusJakarta.variable} ${kumbh.variable}`}>
        <BootstrapClient />
        <Preloader />
        <Sidebar />
        <Search />
        <Header />
        <main id="content">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
